[tool.poetry]
name = "biocypher-project-template"
version = "0.5.43"
description = "Template for creating a BioCypher-driven knowledge graph"
authors = [
    "Sebastian Lobentanzer <sebastian.lobentanzer@gmail.com>",
    "Andreas Maier <andreas.maier-1@uni-hamburg.de>",
]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
biocypher = "^0.9.1"
ipykernel = "^6.29.5"
ontoweaver = "^0.1.3"
pytest-cov = "^6.0"
sqlalchemy = "^2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = ">=6.0"
pre-commit = ">=2.17.0"
ruff = "^0.2.0"
