# add your desired knowledge graph components here
# Authors:  Matthieu Najm - Edwin Carreño

#--- Ontology: BioLink


#--------------------  Information about Nodes
source:
    is_a: protein
    represented_as: node
    input_label: source_protein # temporary node type
    properties:
        genesymbol: str
        ncbi_tax_id: int
        entity_type: str

target:
    is_a: protein
    represented_as: node
    input_label: target_protein # temporary node type
    properties:
        genesymbol: str
        ncbi_tax_id: int
        entity_type: str

protein:
    represented_as: node
    input_label: protein # final_type node type
    properties:
        genesymbol: str
        ncbi_tax_id: int
        entity_type: str


#--------------------  Information about Edges
protein protein interaction:
    is_a: pairwise molecular interaction
    represented_as: edge
    input_label: protein_protein_interaction
    properties:
        is_directed: int8
        is_stimulation: int8
        is_inhibition: int8
