# add your desired knowledge graph components here

source:
    is_a: protein
    represented_as: node
    # preferred_id: uniprot
    input_label: source
    # properties:

target:
    is_a: protein
    represented_as: node
    # preferred_id: doid
    input_label: target

protein protein interaction:
    is_a: pairwise molecular interaction
    represented_as: edge
    input_label: blabla
