name: Tests and Code Quality

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Test on different OS
    runs-on: ${{ matrix.os }}
  tests_and_code_quality:
    runs-on: ubuntu-latest
    steps:
    #----------------------------------------------
    #  Checkout repo and set up Python and Poetry
    #----------------------------------------------ssss
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Setup Python and Poetry
      uses: ./.github/actions/initial_setup

    #----------------------------------------------
    #            Install dependencies
    #----------------------------------------------
    - name: Install Dependencies
      uses: ./.github/actions/install

    #----------------------------------------------
    #      Run tests and code quality checks
    #----------------------------------------------
    - name: Run Tests
      uses: ./.github/actions/test
